# config/app.yml for rails-settings-cached
defaults: &defaults
  token: false,
  refresh_token: false,
  expires_at: 1
  expires: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
